### ISSUE TITLE
Store nlsolve result object in solution?

### ISSUE THREAD

**Issue by tkf** [SciML/SteadyStateDiffEq.jl#16]
Currently, the result object returned by `nlsolve` is thrown away.  It would be nice if the `nlsolve` result is attached to the diffeq solution object so that information about the solution (e.g., trace) can be retrieved.

https://github.com/JuliaDiffEq/SteadyStateDiffEq.jl/blob/62f808282653b7bcb4a7e7fc6e72e4f797739336/src/algorithms.jl#L6

**Comment by ChrisRackauckas** [comment]
Yeah, that sounds like a good idea.
